#! /usr/bin/env python

import os
import sys
import errno
import argparse

from subprocess import Popen, PIPE
from datetime import date

bucketName = 'ajay-test-bucket01'
parser = argparse.ArgumentParser()

def get_current_date():
    return date.today().isoformat()

def backup(localDir):
    parentDirLocal = '/'.join(localDir.split('/')[:-1])
    backupDate = get_current_date()
    s3Dir = "s3://%s/%s%s/" % (bucketName, backupDate, parentDirLocal)
    print "Backing Up %s to %s" % (localDir, s3Dir)
    cmd = "s3cmd sync %s %s" % (localDir, s3Dir)
    print "Command: %s" % cmd
    if run_cmd(cmd):
        print "Backup Successful!"
    else:
        print "Backup Failed!"

def restore(localDir, restoreDate):
    parentDirLocal = '/'.join(localDir.split('/')[:-1])
    directory = localDir.split('/')[-1]
    s3Dir = "s3://%s/%s%s" % (bucketName, restoreDate, localDir)
    print "Restoring %s to %s/%s from date %s" % (s3Dir, parentDirLocal, \
            directory, restoreDate)
    cmd = "s3cmd sync %s %s" % (s3Dir, parentDirLocal)
    print "Command: %s" % cmd
    if run_cmd(cmd):
        print 'Restore Success!'
    else:
        print 'Restore Fail!'

def run_cmd(cmd):
    p = Popen(cmd, shell=True, stdout=PIPE, stderr=PIPE)
    out, err = p.communicate()
    if err:
        print err
        return False
    else:
        print out
        return True

def exit(exitcode):
    print "---"
    parser.print_help(sys.stderr)
    sys.exit(exitcode)

def program_exists(name):
    p = Popen(['/usr/bin/which', name], stdout=PIPE, stderr=PIPE)
    p.communicate()
    return p.returncode == 0

def main():
    parser.add_argument('-d', '--directory', help='directory to be backed up \
            or restored to. Absolute path.')
    parser.add_argument('-b', '--backup', action='store_true')
    parser.add_argument('-l', '--list', action='store_true')
    parser.add_argument('-r', '--restore', action='store_true')
    parser.add_argument('-t', '--date', help='date from which to restore.')
    args = parser.parse_args()

    if not program_exists('s3cmd'):
        print "Missing s3cmd."
        print "Steps to install:"
        print "git clone https://github.com/s3tools/s3cmd.git"
        print "cd s3cmd && python setup.py install"
        print "s3cmd --configure"
        sys.exit(1)

    if args.list:
        print "Dirs under bucket: %s" % bucketName
        cmd = "s3cmd ls s3://%s" % bucketName
        run_cmd(cmd)
        sys.exit(0)
    if not args.directory:
        print "Missing parameters. Set <-d/--directory>. Eh?"
        exit(1)
    else:
        if args.backup and args.restore:
            print "Too many flags set. Select one of (-b/--backup, -r/--restore)"
            exit(1)
        elif not args.backup and not args.restore:
            print "Missing flag. Select one of (-b/--backup, -r/--restore)"
            exit(1)
        else:
            localDir = args.directory
            if args.backup:
                backup(localDir)
            elif args.restore:
                if not args.date:
                    print "Missing paramater. Set <-t/--date>. "
                    print "Backup date in YYYY-MM-DD format."
                    exit(1)
                else:
                    restoreDate = args.date
                    restore(localDir, restoreDate)

if __name__ == '__main__':
    main()
